In [1]:
import pandas as pd
import numpy as np
df = pd.DataFrame(
    {
        "name":["tom","jack","alice","bob","allen"],
        "age":[10,20,23,29,50],
        "score":[60.5,80,30.6,70,83.3]
    },index=[1,2,3,4,5],columns=["name","score","age"]
)
df

    name  score  age
1    tom   60.5   10
2   jack   80.0   20
3  alice   30.6   23
4    bob   70.0   29
5  allen   83.3   50

In [3]:
print(df.head())
print(df.tail(1))

    name  score  age
1    tom   60.5   10
2   jack   80.0   20
3  alice   30.6   23
4    bob   70.0   29
5  allen   83.3   50
    name  score  age
5  allen   83.3   50

In [5]:
print(df.isin(['jack']))#查看元素是否包含在元素集合中

    name  score    age
1  False  False  False
2   True  False  False
3  False  False  False
4  False  False  False
5  False  False  False

In [6]:
print(df.isna())

    name  score    age
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False

In [10]:
print(df['score'].sum())
print(df.score.max())
print(df.score.min())
print(df.score.mean())
print(df.score.median())
print(df.score.mode())

324.4
83.3
30.6
64.88
70.0
0    30.6
1    60.5
2    70.0
3    80.0
4    83.3
Name: score, dtype: float64

In [12]:
print(df.score.std())#标准差
print(df.score.var())#方差
print(df.score.quantile(0.25))#分位数

21.14490482362122
447.10699999999997
60.5

In [14]:
print(df.describe())

           score        age
count   5.000000   5.000000
mean   64.880000  26.400000
std    21.144905  14.876155
min    30.600000  10.000000
25%    60.500000  20.000000
50%    70.000000  23.000000
75%    80.000000  29.000000
max    83.300000  50.000000

In [17]:
print(df.duplicated(subset=['age']))#检查重复

1    False
2    False
3    False
4    False
5    False
dtype: bool

In [19]:
#随机采样
df.sample(2)

   name  score  age
4   bob   70.0   29
2  jack   80.0   20

In [21]:
print(df.replace(15,30))

    name  score  age
1    tom   60.5   10
2   jack   80.0   20
3  alice   30.6   23
4    bob   70.0   29
5  allen   83.3   50

In [22]:
df

    name  score  age
1    tom   60.5   10
2   jack   80.0   20
3  alice   30.6   23
4    bob   70.0   29
5  allen   83.3   50

In [24]:
df.cumsum()

                   name  score  age
1                   tom   60.5   10
2               tomjack  140.5   30
3          tomjackalice  171.1   53
4       tomjackalicebob  241.1   82
5  tomjackaliceboballen  324.4  132

In [26]:
#排序
print(df.sort_index(ascending=False))

    name  score  age
5  allen   83.3   50
4    bob   70.0   29
3  alice   30.6   23
2   jack   80.0   20
1    tom   60.5   10

In [28]:
print(df.sort_values(by='name'))

    name  score  age
3  alice   30.6   23
5  allen   83.3   50
4    bob   70.0   29
2   jack   80.0   20
1    tom   60.5   10

In [32]:
print(df.sort_values(by=['score','age'],ascending=[False,True]))#多行排列

    name  score  age
5  allen   83.3   50
2   jack   80.0   20
4    bob   70.0   29
1    tom   60.5   10
3  alice   30.6   23

In [34]:
df.nlargest(2,columns=['score','age'])#返回最大值
df.nsmallest(2,columns=['score','age'])#返回最小值

    name  score  age
3  alice   30.6   23
1    tom   60.5   10