##dataframe的创建方式

In [11]:
import pandas as pd
import numpy as np
#通过series来创建
s1 = pd.Series([1,2,3,4,5,6])
s2 = pd.Series([4,5,6,7,8,9])
df = pd.DataFrame({"第一列：":s1,"第二列":s2})
df

   第一列：  第二列
0     1    4
1     2    5
2     3    6
3     4    7
4     5    8
5     6    9

In [15]:
#通过字典来创建
df = pd.DataFrame(
    {
        "name":["tom","jack","alice","bob","allen"],
        "age":[10,20,23,29,50],
        "score":[60.5,80,30.6,70,83.3]
    },index=[1,2,3,4,5],columns=["name","score","age"]
)
df

    name  score  age
1    tom   60.5   10
2   jack   80.0   20
3  alice   30.6   23
4    bob   70.0   29
5  allen   83.3   50

In [19]:
#dataframe的属性
print('行索引：')
print(df.index)
print('列索引：')
print(df.columns)
print('值：')
print(df.values)

行索引：
Index([1, 2, 3, 4, 5], dtype='int64')
列索引：
Index(['name', 'score', 'age'], dtype='object')
值：
[['tom' 60.5 10]
 ['jack' 80.0 20]
 ['alice' 30.6 23]
 ['bob' 70.0 29]
 ['allen' 83.3 50]]

In [25]:
print('维度：',df.ndim)
print('形状：',df.shape)
print('元素个数：',df.size)
print('数据类型:')
print(df.dtypes)

维度： 2
形状： (5, 3)
元素个数： 15
数据类型:
name      object
score    float64
age        int64
dtype: object

In [27]:
#行列转置
print(df.T)

          1     2      3     4      5
name    tom  jack  alice   bob  allen
score  60.5  80.0   30.6  70.0   83.3
age      10    20     23    29     50

In [30]:
#获取元素  loc iloc at iat
#获取某行
print(df.loc[4])
print(df.iloc[3])

name      bob
score    70.0
age        29
Name: 4, dtype: object
name      bob
score    70.0
age        29
Name: 4, dtype: object

In [33]:
#获取某列
print(df.loc[:,'name'])
print(df.iloc[:,0])

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object

In [37]:
#单个元素
print(df.at[3,'score'])
print(df.iloc[2,1])
print(df.loc[3,'score'])
print(df.iloc[2,1])

30.6
30.6
30.6
30.6

In [40]:
#获取单列数据
print(df['name'])
print(df.name)
print(df[['name','age']])

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
    name  age
1    tom   10
2   jack   20
3  alice   23
4    bob   29
5  allen   50

In [43]:
#查看部分数据
print(df.head(2))

   name  score  age
1   tom   60.5   10
2  jack   80.0   20

In [46]:
#使用布尔索引筛选数据
df[df.score>70]
df[ (df.score>70)&(df.age<20)]

Empty DataFrame
Columns: [name, score, age]
Index: []

In [49]:
#随机抽样
df.sample()

    name  score  age
3  alice   30.6   23