In [2]:
#数据分箱  pd.cut(x,bins,labels)
import pandas as pd
df = pd.read_excel('students.xlsx')
df.head()

    id  姓名 性别  年龄  地址
0  NaN  张三  男  20  江苏
1  1.0  张三  男  20  江苏
2  2.0  里斯  女  22  江苏

In [5]:
df1 = df.head(2)[['id','姓名']]
df1

    id  姓名
0  NaN  张三
1  1.0  张三

In [18]:
pd.cut(df['id'],bins=2).value_counts()#bins=整数，分成n段区间,起始值，结束值是所有数据的最小值·最大值
df['年龄阶段'] = pd.cut(df['年龄'],bins=[19,19.5,20,21,22.5],labels=['年轻','中年','壮年','少年'])#bins=list,分成n段区间
pd.qcut(df['年龄'],1).value_counts()#等频率分

年龄
(19.999, 22.0]    3
Name: count, dtype: int64

In [22]:
#df.rename()    df.set_index()    df.reset_index()
df = pd.DataFrame({
    'name':['jack','alice','tom','bob'],
    'age':[20,30,40,50],
    'gender':['female','male','female','male']
})
df.set_index('name')
df.reset_index()
df.rename(columns={"age":"年龄"},index={0:4})

    name  年龄  gender
4   jack  20  female
1  alice  30    male
2    tom  40  female
3    bob  50    male

In [24]:
df.index=[1,2,3,4]
df.columns=["姓名","年龄","性别"]
df

      姓名  年龄      性别
1   jack  20  female
2  alice  30    male
3    tom  40  female
4    bob  50    male